### ISSUE TITLE
ClanLib 2.2 for super methane brothers

### ISSUE THREAD

**Issue by nixinator** [sphair/ClanLib#114]
Was trying to get super methane brothers to compile from the dead again.

https://sourceforge.net/projects/methane/

However it needs ClanLib 2.2 , as clanlib.org as down currently there probably no hope this game building from source again. Options are to patch methane brothers to use more recent version of clanlib.

**Comment by rombust** [comment]
Hiya. I am the author of Super Methane Brothers (SMB). Yes, the version on sourceforge does require ClanLib 2.2. Although I still have a copy of ClanLib 2.2 in archive, I prefer it to stay that way, in archive. The current version of ClanLib (v4.0) has now stabilised and is unlikely to change ever.

The version of SMB on sourceforge is actually an older version. I have improved it since then to support ClanLib 4.0. However due to lack of motivation, I didn't complete it. I will have a look at updating it. It should be straightforward. I will post here when complete.

**Comment by nixinator** [comment]
Excellent news, I have the latest clanlib master compiled and packaged, so let me know if you get methane running again and i will package it up for all to enjoy.

**Comment by rombust** [comment]
You can find the updated methane brothers here: https://github.com/rombust/Methane
You will require the updated ClanLib 4.1 patch that I applied today, else sound will not play.
Next week, I will update the sourceforge website reflect the new location of the source code.
You also will require "libmikmod-config" and"libmikmod-dev" also installed and compile Methane.
Enjoy!

Plus I better update the samples at some point to use the Amiga CD32 version. The Amiga 500 version sounds very dated!

**Comment by nixinator** [comment]
Thanks rombust!!!!!!!!!!!!!!!!!... that's great.. I'll see how i  get on with packaging this up this weekend. :-) 

Oh how i miss my Amiga 500 and My Atari ST , devpac , 68000 assembler.. 

simpler days!
