### ISSUE TITLE
Dynamic library configuration

### ISSUE THREAD

**Issue by Xottab-DUTY** [sphair/ClanLib#90]
It would be nice if one could compile this library as a dynamic library.

**Comment by rombust** [comment]
Assuming you are talking about the Microsoft Windows platform.

In the distant past, we used to be able to compile as a DLL. We removed it because
 1) Nobody using ClanLib required it
 2) It was problematic, and it complicated development (I cannot remember the details why).
 3) ClanLib is relatively small, there is little gain is sharing the library, when static linking is only about a 1MB.

**Comment by Xottab-DUTY** [comment]
I'm talking not about only Windows. On Linux there's .so libraries =)
Yup, basically I mean shared library when I said dynamic
By the way, I've managed to compile it as DLL, but didn't try to use it. But I think that I will face with problems.

So, pretty soon I refused my DLL configuration. Will go other way. 😃

**Comment by rombust** [comment]
Static and shared libraries should both work on Linux :)

**Comment by Xottab-DUTY** [comment]
Wow, didn't know about that. Just didn't tried to compile it on Linux for now)
